### ISSUE TITLE
Create MySQL Database

### ISSUE THREAD

**Issue by jhuang15** [Elizabethccc/SearchParty#8]
--Install proper servers if needed (mamp, etc) to connect to database 
--Create database class and database handler if needed
--Follow the tables (attached later) and recreate in database 
--Determine primary key

**Comment by htking1195** [comment]
created the database using amazon web services, MySQL workbench, and phpmyadmin. first step was creating a database instance on AWS so that the information in the database could be hosted and stored on their server. next step was linking the database to mySQL and phpmyadmin using the database endpoint which was created using AWS. using the endpoint you can manage the database using mySQL and phpmyadmin.
